name: build-windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [windows-latest]

    steps:
        # 拉取代码
      - name: Checkout
        uses: actions/checkout@v6.0.2

        # 安装qt环境
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64
    
        # 配置msvc
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x64

        # 安装Ninja
      - name: Install Ninja
        run: choco install ninja

        # CMake 配置
      - name: Configure CMake
        shell: cmd
        run: |
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.29
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%Qt5_DIR%

      - name: Check MSVC version
        shell: cmd
        run: cl

        # 编译
      - name: Build
        shell: cmd
        run: cmake --build build

        # 拉取动态库
      - name: Deploy Qt
        run: |
          mkdir deploy
          copy bin\DQToolKits.exe deploy\
          windeployqt deploy\DQToolKits.exe

        # 发布包
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ToolKit-windows
          path: deploy