name: build-windows

on:
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:


jobs:
  build:
    runs-on: [windows-latest]

    steps:
        # 拉取代码
      - name: Checkout
        uses: actions/checkout@v6.0.2

        # 安装qt环境
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          cache: true

        # 配置msvc
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x64

        # 安装Ninja
      - name: Install Ninja
        run: choco install ninja

        # CMake 配置编译
      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.29
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%Qt5_DIR%
          cmake --build build

        # 拉取动态库
      - name: Deploy Qt
        run: |
          mkdir deploy\bin
          copy bin\DQToolKits.exe deploy\bin
          copy bin\style.qss deploy\bin
          Copy-Item -Path bin\tools -Destination deploy\bin\tools -Recurse -Force

          windeployqt deploy\bin\DQToolKits.exe

        # 发布包
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ToolKit-windows
          path: deploy
