name: Release

on:
  push:
    tags:
      - 'release-*'   # 只有打 tag 才触发

jobs:
  build-and-release:
    runs-on: [windows-latest]

    steps:
        # 拉取代码
      - name: Checkout
        uses: actions/checkout@v6.0.2

        # 提取版本号
      - name: Extract version
        id: vars
        run: |
            echo "VERSION=${GITHUB_REF_NAME#release-}" >> $GITHUB_ENV

        # 安装qt环境
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          cache: true

        # 配置msvc
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x64

        # 安装Ninja
      - name: Install Ninja
        run: choco install ninja

        # CMake 配置编译
      - name: Configure CMake
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=14.29
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%Qt5_DIR%
          cmake --build build

        # 拉取动态库
      - name: Deploy Qt
        run: |
          New-Item -ItemType Directory -Force -Path release/bin
          Copy-Item bin/DQToolKits.exe release/bin
          Copy-Item -Path bin/tools -Destination release/bin/tools -Recurse -Force

          windeployqt release/bin/DQToolKits.exe

        # 文件打包
      - name: Zip
        shell: powershell
        run: |
            Compress-Archive -Path release/* -DestinationPath "DQToolKit-${env:VERSION}-win.zip"

        # 草稿发布
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
            files: DQToolKit-${{ env.VERSION }}-win.zip
            draft: true
    